name: kathymiranda
favicon: null
layout_spectrum: 0.5733141079545021
typography_spectrum: 0.7876131411176175
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.818575220182538
  lightness: 0.08784178923815489
  saturation: 0.7927212461363524
  rhythmicContrast: 0.5737609115894884
purpose: []
